# Generated by Django 4.1.6 on 2023-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_cartoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
