# Generated by Django 4.1.6 on 2023-02-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_cartoon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_250',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('manufacturing_date', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
            ],
        ),
    ]
