# Generated by Django 4.1.6 on 2023-04-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_alter_movie_manufacturing_date'),
    ]

   
