# Generated by Django 4.1.6 on 2023-04-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_top_250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_250',
        ),
    ]
