# Generated by Django 4.1.7 on 2023-05-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_delete_top_250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartoon',
        ),
    ]
