# Generated by Django 4.1.6 on 2023-05-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0017_alter_klient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
